# docker compose up --detach --build --force-recreate --remove-orphans
services:
    web:
        image: architecture/web
        container_name: architecture_web
        restart: always
        build:
            context: .
        environment:
            - SigningKey=58a97cd766d741e8a21b8d3c4279652469801dc8da844fa5bf80afeea85aa472
            - ConnectionStrings__Context=Server=architecture_database;Database=Database;User Id=sa;Password=P4ssW0rd!;TrustServerCertificate=true;
            - Serilog__WriteTo__1__Args__path=/app/logs/
        depends_on:
            - database
        ports:
            - 8090:8080
    database:
        image: mcr.microsoft.com/mssql/server
        container_name: architecture_database
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P4ssW0rd!
        ports:
            - 1433:1433
        volumes:
            - database:/var/opt/mssql
volumes:
    database:
